### ISSUE TITLE
Support RTMPS

### ISSUE THREAD

**Issue by quarterpi** [membraneframework/membrane_rtmp_plugin#36]
Hi, I've been trying to implement RTMPS by placing a Ranch SSL server in front of Membrane RTMP. I'm stuck at trying to pass control of the socket to Membrane. I get this error ```** (FunctionClauseError) no function clause matching in :inet_db.lookup_socket/1
    (kernel 8.3.2) inet_db.erl:823: :inet_db.lookup_socket({:sslsocket, {:gen_tcp, #Port<0.47>, :tls_connection, [option_tracker: #PID<0.4088.0>, session_tickets_tracker: :disabled, session_id_tracker: #PID<0.4089.0>]}, [#PID<0.5788.0>, #PID<0.5787.0>]})``` which seems to boil down to `gen_tcp.controlling_process/2`. For ssl we would need to add another clause for `ssl.controlling_process/2` from what I can tell. Is this a possibility? I'm happy to help if I can.

**Comment by Qizot** [comment]
I didn't look into the secure variant of `RTMP` but just changing `ssl.controlling_process` is not enough as the `Source` element relies on `tcp_*` pattern matches in incoming socket messages and no `ssl_*`. It would require some additional configuration to allow for SSL connections, e.g. starting different receiving loop [here](https://github.com/membraneframework/membrane_rtmp_plugin/blob/02f38e1349f111bdfc528707236cf958fa339da4/lib/membrane_rtmp_plugin/rtmp/source/source.ex#L92). 

If RTMP is only different from RTMPS based on socket type then adding another receiving loop and source options should be fairly easy.

**Comment by quarterpi** [comment]
Thank you @Qizot! I've been playing around with this and it seems that `:gen_tcp` is more deeply entrenched than I originally thought. I'll keep at it and see what I can come up with. Hopefully I don't hit an impasse.

**Comment by quarterpi** [comment]
@Qizot I came to the conclusion that it was better to write an rtmps plugin than to modify the rtmp plugin to accept both rtmp and rtmps. I am now able to stream rtmps successfully! I wouldn't say it is prod ready just yet, but I didn't change that much. Is this something that the community would be interested in? I'm not sure what the next steps would be?

**Comment by Qizot** [comment]
If RTMPS is all about passing and receiving messages from a different socket (SSL one) I guess we could simply add that to RTMP implementation quite easily.

**Comment by quarterpi** [comment]
Now that I have it working, I can try merging the two if you think that makes sense? Would you prefer to have them both in one plugin or two separate plugins?
The obvious downside to having two separate plugins is that any changes to the underlying RTMP module would have to be duplicated across them both (seems like it could turn into a maintenance nightmare).

**Comment by Qizot** [comment]
I guess having a flag `use_ssl?` or something similar should be enough to keep it in a single module as besides this receiving loop that I pointed out earlinger not much will change.

**Comment by Qizot** [comment]
Done by #40
