### ISSUE TITLE
MessageValidator API does not support stateful validators

### ISSUE THREAD

**Issue by dmorn** [membraneframework/membrane_rtmp_plugin#47]
Given the API provided in https://github.com/membraneframework/membrane_rtmp_plugin/blob/master/lib/membrane_rtmp_plugin/rtmp/source/message_validator.ex, it is not possible to design a stream validator that has a state, e.g. a pre-shared RTMP stream key that the server is going to accept. I would propose to redesign it as a Protocol!

**Comment by dmorn** [comment]
This is how it looks like: https://github.com/kim-company/membrane_rtmp_plugin/commit/1dc8317f0e525a5f735e9483037f22b5fbd888ea. I can make a PR if you think that this approach may suit developer's needs better.

**Comment by DominikWolek** [comment]
Hey @dmorn, you can open a PR to this repo
